### ISSUE TITLE
Add information about thread-safety to the README/docs?

### ISSUE THREAD

**Issue by joscarsson** [billziss-gh/cgofuse#26]
Thanks for a great library!

Perhaps it is obvious for others, but I was wondering about thread-safety and the different callback methods. Is it on the implementor of the `FileSystemInterface` to protect data structures, or is it done by the library? In the `Passthrough` example, nothing is protected while in `Memfs` all methods are protected behind a single `Mutex`. Is it because the thread-safety is guaranteed by the underlying filesystem in the `Passthrough` case?

Would be nice to have some mention of this in the README/godoc reference.

**Comment by billziss-gh** [comment]
FUSE file systems are expected to protect their own data structures, unless the `-s` switch is passed which instructs the FUSE layer to serialize requests. This is true of cgofuse as well.

I will add this to the documentation.

**Comment by joscarsson** [comment]
Thanks!

**Comment by billziss-gh** [comment]
Finally added this to the documentation: 6b4bd137607ec423738e89f860118447083a5352

Sorry for the long delay.
