### ISSUE TITLE
Push a new version of billziss/xgo-cgofuse?

### ISSUE THREAD

**Issue by joscarsson** [billziss-gh/cgofuse#27]
I tried cross-compiling using the billziss/xgo-cgofuse Docker image, but it fails due to too old go version. I then tried using the `Dockerfile` in the repo instead, and built the image locally - that worked. I think all that is missing is a new version of billziss/xgo-cgofuse pushed to the Docker registry.

**Comment by vansante** [comment]
Im having the same problem

**Comment by jannson** [comment]
You can build yourself with the Dockerfile in source code.

**Comment by billziss-gh** [comment]
The xgo-cgofuse image is now regularly built using DockerHub.

https://hub.docker.com/r/billziss/xgo-cgofuse/builds

**Comment by ncw** [comment]
I note that the base [xgo](https://hub.docker.com/r/karalabe/xgo-latest/builds) has had a new release but docker hub hasn't rebuild xgo-cgofuse...

**Comment by billziss-gh** [comment]
i can kick start this manually, but thought that this was the benefit of Docker’s infra?

**Comment by ncw** [comment]
> I can kick start this manually, but thought that this was the benefit of Docker’s infra?

Yes me too!

**Comment by billziss-gh** [comment]
I manually triggered a new build.

But I seem to recall that there was a standing bug in the Docker infrastructure regarding this? I think we had this discussion somewhere else (perhaps in an rclone issue).

**Comment by ncw** [comment]
> I manually triggered a new build.

Thank you :-)

> But I seem to recall that there was a standing bug in the Docker infrastructure regarding this? I think we had this discussion somewhere else (perhaps in an rclone issue).

Hmm, yes I think I remember reading this somewhere...
