### ISSUE TITLE
O_RDONLY and friends are missing

### ISSUE THREAD

**Issue by ncw** [billziss-gh/cgofuse#3]
Normally I'd read O_RDONLY from syscall, but I don't think that will work on Windows, so thsese constants need to be duplicated in cgofuse.

These are necessary when working out which mode to open a file in (read or write) when the flags just can't be passed on.

**Comment by ncw** [comment]
If you want I'll send a PR for this - I just wanted to make a note of this before a forgot!

**Comment by billziss-gh** [comment]
Good catch. We would have to make it cross-platform (constants are not same on UNIX and Windows). 

If you have the code ready you can send a PR. Otherwise I will add it and make sure it is correct on all supported platforms.

**Comment by billziss-gh** [comment]
Ok, I am finishing some testing using `CGODEBUG=cgocheck=2` (as per your suggestion in the rclone issue) and I will add those flags.

**Comment by billziss-gh** [comment]
Commit 67b4cc0079281d71c50adc57badb53685a84f225 just added these flags. Testing it now.

**Comment by billziss-gh** [comment]
Merged into master.

**Comment by ncw** [comment]
Super - thank you :-)

O_ACCMODE would be useful too for masking whether the mode is read or write.  Here is the [libc doc](https://www.gnu.org/software/libc/manual/html_node/Access-Modes.html) it says GNU only, but it is mentioned in the [posix fnctl docs](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/fcntl.h.html).  Note sure whether that is supported on Windows though.

**Comment by billziss-gh** [comment]
MSVC does not define `O_ACCMODE`. It turns out that Mingw does as:

```C
#define _O_ACCMODE (_O_RDONLY|_O_WRONLY|_O_RDWR)
```

So I will add a similar definition to `fuse.go`.

**Comment by billziss-gh** [comment]
Added with commit 3650807204ba06ebebf426b2a22b0f4b177ff595.

Please note that on Windows `O_RDONLY == 0`, `O_WRONLY == 1` and `O_RDWR == 2`. So do not assume that `O_RDONLY|O_WRONLY == O_RDWR`.

**Comment by ncw** [comment]
That seems very sensible - thanks :+1:
