### ISSUE TITLE
Delete Folder with Files is not calling Rmdir

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/cgofuse#32]
When I delete a Folder which contains one or more Files, the callback Rmdir is not called on Folder. Only the Unlink is called for all the files in that Folder. 

Any idea or workaround for this issue?

**Comment by billziss-gh** [comment]
I am suspecting a problem with either how you set user permissions on your files (e.g. are you using the `-o uid=UID,gid=GID` options?) or perhaps a problem with the file system itself.

Are you running the file system with the `-d` option to get debug output and see what file system requests you receive from the operating system?

**Comment by mohankumarv2005** [comment]
Thank you for your response. Yes, we are using following options to Mount.
 
options := []string{"-o", "volname=Altair", "-o", "uid=-1", "-o", "gid=-1"}
host.Mount(mountDrive, options)
 
Also, surprisingly when I started the file system with “-d” option, I see Rmdir() being called correctly on the selected folder and therefore no issues with Delete.
 
Any thoughts on how starting in debug mode having an effect on invoking Rmdir() Callback?

**Comment by billziss-gh** [comment]
In my opinion this strongly suggests that there is a problem with your file system.

There is no functional difference when running with the -d option. The WinFsp DLL simply logs all requests/responses from/to the kernel to stderr.
