### ISSUE TITLE
Connect to docker hub to auto build the container

### ISSUE THREAD

**Issue by ncw** [billziss-gh/cgofuse#37]
Is there any chance you could connect this repo to the docker hub to make [automated builds](https://docs.docker.com/docker-hub/builds/) of the container?

I did it [recently with rclone](https://hub.docker.com/r/rclone/rclone) and the process was quite straight forward :-)

It makes a build on every push to the repo and you can set it to build when upstream containers change too.

Thanks

Nick

**Comment by billziss-gh** [comment]
@ncw this looks interesting, but I currently have too much work on other projects to look into this more closely. If you need this in a hurry and you already have the know-how would you consider submitting a PR? (I know you are probably too busy with rclone, etc. yourself.)

**Comment by ncw** [comment]
It isn't something you can do with a PR it needs permissions granting on this repo to the docker hub organization.  After that it is just clicking some buttons!

I could add it to the rclone docker hub but I think you'd need to make me a member of this repo.

My plan B was to fork this repo (under github.com/rclone) and set up an auto build on the rclone docker hub which will suit my purposes for building rclone and others could find the docker image there if they wanted.  I'll do this anyway and post a link so you can see what it looks like.

**Comment by billziss-gh** [comment]
@ncw, I will look into this today.

**Comment by billziss-gh** [comment]
BTW, dumb question, but by "container" you mean "xgo-cgofuse". Is this correct?

**Comment by billziss-gh** [comment]
This eventually has finished successfully:

https://hub.docker.com/r/billziss/xgo-cgofuse

I probably should add some tests to verify that the resulting docker file works indeed.

Let me know if this is what you wanted. I will devote a few more hours on cgofuse to clean it up and make sure that it properly builds on the different CI systems.

**Comment by billziss-gh** [comment]
I believe this is now complete and new xgo-cgofuse images are built after every commit to master.

While I was at it I ended up cleaning up the project and its README and made sure that it works on all CI systems (most CI build were broken because of changes in the CI environment -- e.g. new OS versions that restrict loading kexts on macOS, etc.)

Let me know if this is what you wanted, so we can close this.

**Comment by ncw** [comment]
That is perfect, thanks Bill :-)

Yes docker hub seems very slow! However I was told by an rclone contributor that builds done by docker hub are preferred by many people because of the assurances they give.

I'll plug your new container into the rclone build process.

Did you tick the rebuild if the upstream changes button? That would need useful here I think.

You could put a button like this in the readme

 [![Docker Pulls](https://img.shields.io/docker/pulls/rclone/rclone)](https://hub.docker.com/r/billziss/xgo-cgofuse)

**Comment by billziss-gh** [comment]
> Did you tick the rebuild if the upstream changes button? That would need useful here I think.

Where is this setting. I am fairly certain I saw it yesterday, but can no longer find it today.

**Comment by ncw** [comment]
Do you think this would give a significant advantage over not using cgo?  I guess it still has the same syscall overhead and need for dynamic libraries, however it doesn't need a C compiler - would you agree with that?

I haven't tried out the Windows nocgo interface yet - do you think that would be a good choice for rclone?

BTW I plugged the new container into rclone's build process - it is working very well - thanks!

**Comment by billziss-gh** [comment]
I think not needing a C compiler would be the big win here.

> I haven't tried out the Windows nocgo interface yet - do you think that would be a good choice for rclone?

It depends on how you use cgofuse. If you use it only for Windows, then it might allow you to stop using cgo and go back to go (i.e. nocgo) builds. If you use it for other platforms, then IMO it is not worth changing, because you need a C compiler on those platforms anyway.

**Comment by ncw** [comment]
> It depends on how you use cgofuse. If you use it only for Windows, then it might allow you to stop using cgo and go back to go (i.e. nocgo) builds. If you use it for other platforms, then IMO it is not worth changing, because you need a C compiler on those platforms anyway.

I build the Windows binary natively on Windows so it probably isn't worth switching for rclone. It is a very welcome development though and I'll use it for my next go/fuse project for definite!
