### ISSUE TITLE
Some "defer recover()" uses are no-ops.

### ISSUE THREAD

**Issue by go101** [billziss-gh/cgofuse#39]
Ref: https://github.com/golang/go/issues/34530

**Comment by go101** [comment]
More accurately, they are no-ops for the expected use cases.

**Comment by billziss-gh** [comment]
Doh! You are correct of course!

**Comment by billziss-gh** [comment]
I added commit f76abb9a1d876bdf8f0a60ed28cd9dd7d0b3bf0c, which should fix this issue.
