### ISSUE TITLE
Specify user defined value for Type field in Windows Explorer

### ISSUE THREAD

**Issue by mohankumarv2005** [billziss-gh/cgofuse#40]
Hi,

I would like to how to specify user defined value for Type field shown in Windows Explorer for Files/Folders instead of just showing "File folder" for Directory & "Text Document" for Text File.

My requirement is to set a user defined value for a Directory let's say to "My Folder Type" and for a Text File to "My Text File" in Type fields.

Please see the attachment for reference.

Thanks,
Mohan
![Snap](https://user-images.githubusercontent.com/34312022/67961425-b0b0ae00-fc21-11e9-9893-8b709c4f3591.png)

**Comment by billziss-gh** [comment]
This is not something that is done via a file system. In general Explorer uses the file extension to determine the file type.
