### ISSUE TITLE
MemFS example fails with certain Windows programs?

### ISSUE THREAD

**Issue by wthorp** [billziss-gh/cgofuse#41]
I'm using Windows 10 Pro (1903).  If I take the memfs example, it first seems that I need to add a Statfs() method to make the filesystem writable.  After that, however, I have an unknown problem with application compatibility.  An MKV will open in "Windows Media Player" but not "Movies & TV".  An MP3 will open with "iTunes" but not "Groove Music".

Unfortunately, I haven't been able to figure out anything more than this.  Am I missing something?

**Comment by billziss-gh** [comment]
Please use latest WinFsp beta to resolve an issue with media playing on latest Windows.

**Comment by wthorp** [comment]
That worked - fantastic!
