### ISSUE TITLE
Queuing OS calls

### ISSUE THREAD

**Issue by thomasbn94** [billziss-gh/cgofuse#43]
This is a question rather than an issue: how do cgofuse manage concurrent invocations? Does each OS invocation run as a separate thread or are they queued on the same thread? For example, if I run multiple instances of ```echo "foo" >> file.txt```, how does the library handle such a case?

**Comment by billziss-gh** [comment]
@thomasbn94 this is a complicated subject that depends on the underlying user-mode and kernel-mode components of the underlying FUSE implementation (recall that cgofuse runs on many different systems).

In general FUSE does not provide you with any thread-safety guarantees, unless you run with the `-s` option which guarantees you serialized requests. So you should assume that you may get concurrent calls on multiple threads and that you must properly protect your file system data structures using appropriate synchronization.
