### ISSUE TITLE
Build Docker image

### ISSUE THREAD

**Issue by thomasbn94** [billziss-gh/cgofuse#44]
I have a project with CGO as one of its dependencies. My Dockerfile looks like this: 

```FROM golang:1.10.6
COPY . /go/src/app
WORKDIR /go/src/app

RUN go get -v -d && \
    go build .

WORKDIR /
COPY --from=0 /go/src/app/build .

EXPOSE 18088

CMD ["/app"]
```
I get this error message after trying to build the image:
```
...
 github.com/billziss-gh/cgofuse/fuse
../github.com/billziss-gh/cgofuse/fuse/host.go:30:8: undefined: c_struct_fuse
```
The Dockerfile is incomplete and runs a single-stage build and is sub-optimal. However, optimizations is due for later. How do you properly build an image with CGO as a part of the build process?

**Comment by billziss-gh** [comment]
It is not clear to me what you are asking.

If you are looking for cross-compilation builds it is best to use xgo as documented [here](https://github.com/billziss-gh/cgofuse#how-to-cross-compile-your-project-using-xgo).

If you are looking to create your own Docker image to build cgofuse based projects then you need to install the prerequisites and then build as documented [here](https://github.com/billziss-gh/cgofuse#how-to-build).

**Comment by tomcat-bit** [comment]
To explain better -- I'm using the current Docker file
```
FROM golang:alpine AS builder
ENV GOBIN $GOPATH/bin
RUN apk update
RUN apk add fuse-dev gcc libc-dev fuse

# Set necessary environmet variables needed for our image
ENV GO111MODULE=auto \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

RUN mkdir -p /go/src/github.com/tomcat-bit/cgofuse
WORKDIR /go/src/github.com/tomcat-bit/cgofuse

COPY go.mod .
COPY go.sum .
RUN go mod download 

COPY . .

RUN go build -a -o /fuser ./examples/passthrough
FROM alpine:latest

RUN apk update
RUN apk add fuse
COPY --from=builder /fuser /
```
I get 
```
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:30:8: undefined: c_struct_fuse
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:64:38: undefined: c_fuse_statvfs_t
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:79:33: undefined: c_fuse_stat_t
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:98:56: undefined: c_fuse_timespec_t
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:103:28: undefined: c_int
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:114:25: undefined: c_char
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:114:40: undefined: c_fuse_stat_t
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:114:62: undefined: c_int
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:124:26: undefined: c_char
/go/pkg/mod/github.com/billziss-gh/cgofuse@v1.4.0/fuse/host.go:124:55: undefined: c_size_t
```
It seems like using Go mod doesn't work with building with fuse. Further, using ```dep``` as described in https://github.com/andersjohansenange/cgofuse/commit/a08ea764875fac530b4270e915a2ea4a61b02dd7 works fine. When it works, I'll probably make a pull request on how to build a Docker image when Go modules is enabled.
