### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by ncw** [billziss-gh/cgofuse#46]
As part of testing #38 I noticed that you haven't made a release for a while.

In the new world of go modules, consumers of this repo will only use your latest tagged versions by default.

There aren't too many commits of significance here but CreateEx and OpenEx is one :-)

https://github.com/billziss-gh/cgofuse/compare/v1.2.0...master

Thank you Bill and hope you are keeping well in these troubled times.

**Comment by billziss-gh** [comment]
Nick, I have made new v1.3.0 release available. It is currently being built in docker hub.

> Thank you Bill and hope you are keeping well in these troubled times.

Thank you! I hope the same for you and your family.

**Comment by ncw** [comment]
Thanks Bill - looks perfect :-)
