### ISSUE TITLE
Issue mounting on fresh-boot/driver-install when called concurrently

### ISSUE THREAD

**Issue by djdv** [billziss-gh/cgofuse#51]
I'm trying to host several different file systems within a single program.
To do this, I construct a `FileSystemHost` for each file system implementation, and then concurrently call their `Mount` method.

Doing so on a fresh boot of the OS, or after installing the driver for the first time, causes cgofuse to log an error to the console (`Cannot create WinFSP-FUSE file system: FSD not found.`), for all but 1 of the `Mount` calls.

This does not happen on subsequent runs.
When run again, each call to `Mount` works as expected under the same conditions.

Demonstration: https://www.youtube.com/watch?v=V0Z_abvSPNs
Modifying memfs's main function gives a simple reproducible:
``` go
func main() {
	memfs1, memfs2, memfs3 := NewMemfs(), NewMemfs(), NewMemfs()
	host1, host2, host3 := fuse.NewFileSystemHost(memfs1), fuse.NewFileSystemHost(memfs2), fuse.NewFileSystemHost(memfs3)

	hostPath := `C:\whatever`
	os.Mkdir(hostPath, 0777)

	for i, hst := range []*fuse.FileSystemHost{host1, host2, host3} {
		go func(index int, host *fuse.FileSystemHost) {
			host.SetCapReaddirPlus(true)
			hostTarget := filepath.Join(hostPath, strconv.Itoa(index))

			fmt.Println("Mounting: ", hostTarget)
			host.Mount(hostTarget, nil)
		}(i, hst)
	}

	semaphore := make(chan struct{})
	<-semaphore
}
```

I've experienced this on versions of Go 1.14 - 1.15 with WinFSP versions 2020 - 2020.2
And assume it's not intended behavior. Although I'm wondering if the client program is expected to gaurd against such a thing (prevent concurrent calls to `Mount` even across different `FileSystemHost` instances)

If I can help provide more context for this, let me know.

**Comment by billziss-gh** [comment]
This does sound like a problem in cgofuse and/or WinFsp-FUSE.

I am very busy right now, but I am hoping to have time to look into it some time in the future.

**Comment by billziss-gh** [comment]
I looked into this a bit more and it appears to be a problem within WinFsp.

The issue is that when the file system driver is not running, the WinFsp DLL (i.e. the user mode portion of WinFsp) will attempt to start the driver. This is not currently done in a thread-safe manner as I never anticipated such a need.

It should be relatively easy to make this thread-safe by wrapping it in a lock. I will add an issue on WinFsp to track this.

**Comment by billziss-gh** [comment]
I have added WinFsp commit billziss-gh/winfsp@2d5d058d2f10de78d759aba4512d195736a5606d that should fix this issue.

**Comment by djdv** [comment]
Thanks for that!
Whether I test out the fix early via a local build or wait until the next beta release, I'll post back about it.

>This is not currently done in a thread-safe manner as I never anticipated such a need.

Makes sense. I figured launching like this wasn't typical.

If you're interested, I'm making this mount-instance / manager-interface thing that takes in a series of requests and issues them via gorotuines, with 1 routine per pair of APIs.

Example:
![fs manager thing](https://user-images.githubusercontent.com/13862850/103823110-6d30ab80-503f-11eb-8d22-e9bb17bdb669.png)

There's no particular reason for it to be that way, it's just how the request pipeline ended up.
The entire request is split into sections and each section basically gets inspected, parsed, and sent to its API handler (via a channel) as soon as it's ready.
Likewise the responses they just come back as early as they can in no particular order.

(Right now those test binaries don't actually do anything, they just response back as if it did, but I'll be adapting the cgofuse stuff I have up to it so soon. Currently thinking about how best to split relevant packages up, some of it _might_ be useful outside of my own needs)

**Comment by djdv** [comment]
Hey there, I missed the beta release tag but just saw the latest 2021 release and wanted to say that the modified memfs example in the first comment seems to work just fine now. 🎉
Thanks again for that!
