### ISSUE TITLE
Virtio-FS disk not showing after upgrade to 1.9 from 1.9B2.

### ISSUE THREAD

**Issue by surfchris** [billziss-gh/cgofuse#56]
When upgrading to 1.9.21096 (release) from 1.9.21033 (beta2) the virtio-fs disk does not show up anymore. Even tried to run "virtiofs.exe -d -1" in the command prompt (with Virtio-FS service disabled) without success.

**Comment by billziss-gh** [comment]
I am not certain what virtiofs is here. But I am certain that it is is not related to cgofuse or WinFsp.

Please report this problem to the appropriate project.
