### ISSUE TITLE
Alternative backends for Windows

### ISSUE THREAD

**Issue by mappu** [billziss-gh/cgofuse#9]
Hi,

WinFSP is a high quality project. But it has a restrictive license, so many project opt for DokanY instead.

Is it possible to choose between multiple backends on Windows?

Another cross-platform FUSE-alike is to host an FTP or WebDAV server, and then, each OS already has some way of mounting it. It might be interesting to support such as a platform-agnostic FUSE-alike backend.

**Comment by mappu** [comment]
I realise you are author of WinFSP, so this is unlikely to be accepted.

**Comment by billziss-gh** [comment]
@mappu thanks for reaching out and for your understanding re: WinFsp. You are right that I would be disinclined to accept an alternative backend for Windows.

[You are also right that the WinFsp license (GPLv3) is somewhat restrictive, although I note that it includes a special exception for open source (FLOSS) projects.]

However I would actually be interested in a WebDAV (or FTP?) FUSE implementation. For example, I have been always intrigued by @rianhunter's [davfuse](https://github.com/rianhunter/davfuse) although I have never tried it and I do not know how well it works.

**Comment by rianhunter** [comment]
It actually works pretty well but it's not very efficient. SMB is a better option, the drawback is that the port that Windows uses to mount SMB is hardcoded.
